---
name: "nixpkgs-review"
on:
  workflow_dispatch:
    inputs:
      pr:
        description: "The PR number to run the review for"
        required: true
        type: number
jobs:
  nixpkgs-review:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - host: ubuntu-20.04
          - host: macos-14
          - host: macos-11
    steps:
    - name: Checkout nixpkgs
      uses: actions/checkout@v4
      with:
        repository: NixOS/nixpkgs
        ref: nixos-unstable
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@v10
    - name: Run nixpkgs-review and post result
      run: nix run .#nixpkgs-review -- pr --post-result ${{ inputs.pr }} --token ${{ secrets.TOKEN }}
